services:
  frontend:
    image: salimabouhamidi/frontend-app
    ports:
      - "5174:5173"  
    networks:
      - app-network

  backend:
    image: salimabouhamidi/docker-img-spoto-backend:latest
    ports:
      - "3002:3001"
    environment:
      - DATABASE_URL=mongodb://localhost:27017/sporto
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
